#!/usr/bin/env bash

GIT_DIR="${GIT_DIR:-"$(git rev-parse --show-toplevel)"}"
if [ "$?" != 0 ]; then
    exit "$?"
fi

# Run local git hook if it exists.
if [ -e "$GIT_DIR/.git/hooks/sendemail-validate" ]; then
    eval "$GIT_DIR/.git/hooks/sendemail-validate" $@
    exit "$?"
fi

exit 0
