# Theme: Later This Evening (modificated)
colors:
    black: "#2B2B2B" # "#000000"
    grey: "#3C3D3D"
    white: "#C1C2C2" # "#FFFFFF"

    red: "#D3232F"
    green: "#AABB39"
    yellow: "#FCAE25"
    blue: "#6699D6"
    magenta: "#AB53D6"
    cyan: "#5FC0AE"

    foreground: "#F2F2F2"
    background: "#222222"
    cursor_color: "#282A2E"

    transparent: "#00000000"
