# See: https://terminal.sexy/
# See: https://mayccoll.github.io/Gogh/

import:
    - ./theme.later-this-evening.yml
    # - ./theme.doom-one.yml

colors:
    # Alacritty.
    alacritty:
        primary:
            background: "{{ colors.primary.background }}"
            foreground: "{{ colors.primary.foreground }}"

        cursor:
            text: "{{ colors.primary.cursor_color }}"
            cursor: "{{ colors.primary.foreground }}"

        normal:
            black: "{{ colors.normal.black }}"
            red: "{{ colors.normal.red }}"
            green: "{{ colors.normal.green }}"
            yellow: "{{ colors.normal.yellow }}"
            blue: "{{ colors.normal.blue }}"
            magenta: "{{ colors.normal.magenta }}"
            cyan: "{{ colors.normal.cyan }}"
            white: "{{ colors.normal.white }}"

        bright:
            black: "{{ colors.bright.black }}"
            red: "{{ colors.bright.red }}"
            green: "{{ colors.bright.green }}"
            yellow: "{{ colors.bright.yellow }}"
            blue: "{{ colors.bright.blue }}"
            magenta: "{{ colors.bright.magenta }}"
            cyan: "{{ colors.bright.cyan }}"
            white: "{{ colors.bright.white }}"

    # AwesomeWM
    awesome:
        widgets:
            battery:
                normal: "{{ colors.normal.yellow }}"

            brightness:
                normal: "{{ colors.normal.blue }}"

            cpu:
                normal: "{{ colors.normal.red }}"

            disk:
                normal: "{{ colors.normal.green }}"

            ram:
                normal: "{{ colors.normal.blue }}"

            volume:
                normal: "{{ colors.normal.green }}"
                muted: "{{ colors.normal.red }}"
