colors:
    black: "#272822" # "#000000"
    grey: "#373B41"
    white: "#F2F2F2" # "#FFFFFF"
    red: "#CC6666"
    green: "#B5BD68"
    yellow: "#F0C674"
    blue: "#81A2BE"
    magenta: "#B294BB"
    cyan: "#8ABEB7"

    foreground: "#f2f2f2"
    background: "#1D1F21"
    cursor_color: "#282A2E"

    transparent: "#00000000"
