#!/usr/bin/env bash

# Constants.
declare -A texts
texts[poweroff]="Power-off"
texts[reboot]="Reboot"
texts[suspend]="Suspend"
texts[hibernate]="Hibernate"

declare -A actions
actions[poweroff]="systemctl poweroff"
actions[reboot]="systemctl reboot"
actions[suspend]="systemctl suspend"
actions[hibernate]="systemctl hibernate"

order=(
    poweroff
    reboot
    suspend
    hibernate
)

# Helpers.
rofi_set() {
    echo -en "\0""$1""\x1f""$2""\n"
}

option() {
    echo $@
}

find_key() {
    local name="$1"

    for key in ${!options[@]}; do
        if [ "${texts["$key"]}" = "$name" ]; then
            echo "$key"
            return 0
        fi
    done

    return 1
}

# Main.
if [ ! "$@" = "" ]; then
    key="$(find_key "$@")"
    if [ "$?" != 0 ]; then
        exit "$?"
    fi

    cmd="${actions["$key"]}"
    if [ -z "$cmd" ]; then
        exit 1
    fi

    eval "$cmd"

    exit 0
fi

rofi_set "markup-rows" "true"
for key in ${order[@]}; do
    option "${texts["$key"]}"
done
