#!/bin/sh

set -e
set -u
set -o pipefail

source ~/.config/polybar/lib/colors.sh

res=($(~/bin/vpnstatus))
status="${res[0]}"

if [ ! "$#" = 0 ]; then
    case "$1" in
        toggle)
            if [ "$status" = "connected" ]; then
                sudo systemctl stop openvpn-server.service
            elif [ "$status" = "disconnected" ]; then
                sudo systemctl start openvpn-server.service
            fi

            exit 0
            ;;
    esac
fi

if [ "$status" = "disconnected" ]; then
    echo "%{u${color_red}}%{F${color_red}}VPN%{F-}%{u-}"
    exit 0
fi

active_vpn_name="${res[1]}"
ip="${res[2]}"

vpn_name_color="$color_red"
if [ "$status" = "connected" ]; then
    vpn_name_color="$color_green"
fi

echo "%{u${vpn_name_color}}%{F${color_green}}VPN%{F-}  ${ip}  %{F${vpn_name_color}}$active_vpn_name%{F-}%{u-}"

