#!/usr/bin/env bash

#
# This script generates images for the README.md file.
#

set -e
set -u
set -o pipefail

# Constants.
ROOT="$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")"

# Init.
magick() {
	"$ROOT/scripts/nix-call.sh" magick imagemagick7 $@
}

background="$HOME/.wallpaper"
font="/nix/var/nix/profiles/system/sw/share/X11-fonts/JetBrainsMono-Regular.ttf"
width="1280"
height="640"
offset_x="0"
offset_y="20"
opacity="75"
result="$ROOT/assets/github-social-review.png"

mkdir -p "$(dirname "$result")"

magick "$background" \
	-resize "${width}x" \
	-gravity center \
	-crop "${width}x${height}+${offset_x}+${offset_y}" \
	-fill "\\#000000" \
	-colorize "$opacity" \
	-font "$font" \
	-pointsize 120 \
	-fill "\\#FFFFFF" \
	-annotate +0+32 '\\~/.dotfiles' \
	-pointsize 32 \
	-annotate +232+132 'by\\\ SuperPaintman' \
	"$result"
